apiVersion: v1
data:
  create_db.js: |
    db.createUser( { user: "web-finder", pwd: "test", roles: [ "readWrite", "dbAdmin" ]} )
    db.getSiblingDB('web-finder')
    db.createCollection("option");
kind: ConfigMap
metadata:
  name: create-db-configmap
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
